'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=2.0.50727.1432.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
Partial Public Class Invoices
    
    Private itemsField() As InvoicesInvoiceNumber
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("InvoiceNumber", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Items() As InvoicesInvoiceNumber()
        Get
            Return Me.itemsField
        End Get
        Set
            Me.itemsField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class InvoicesInvoiceNumber
    
    Private filePathsField() As InvoicesInvoiceNumberFilePaths
    
    Private valueField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("FilePaths", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property FilePaths() As InvoicesInvoiceNumberFilePaths()
        Get
            Return Me.filePathsField
        End Get
        Set
            Me.filePathsField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Value() As String
        Get
            Return Me.valueField
        End Get
        Set
            Me.valueField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class InvoicesInvoiceNumberFilePaths
    
    Private invoicePathField As String
    
    Private deliveryTicketPathField As String
    
    Private bOLPathField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property InvoicePath() As String
        Get
            Return Me.invoicePathField
        End Get
        Set
            Me.invoicePathField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property DeliveryTicketPath() As String
        Get
            Return Me.deliveryTicketPathField
        End Get
        Set
            Me.deliveryTicketPathField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property BOLPath() As String
        Get
            Return Me.bOLPathField
        End Get
        Set
            Me.bOLPathField = value
        End Set
    End Property
End Class
