'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=2.0.50727.1432.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
Partial Public Class CustomerInvoiceBatch
    
    Private itemsField() As Object
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Config", GetType(CustomerInvoiceBatchConfig), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
     System.Xml.Serialization.XmlElementAttribute("Customer", GetType(CustomerInvoiceBatchCustomer), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Items() As Object()
        Get
            Return Me.itemsField
        End Get
        Set
            Me.itemsField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class CustomerInvoiceBatchConfig
    
    Private applicationNameField As String
    
    Private logLevelField As String
    
    Private errorLogSourceFileField As String
    
    Private errorLogDestinationField As String
    
    Private companyPlatformIDField As String
    
    Private attachmentField() As CustomerInvoiceBatchConfigAttachment
    
    Private faxField() As CustomerInvoiceBatchConfigFax
    
    Private emailField() As CustomerInvoiceBatchConfigEmail
    
    Private printField() As CustomerInvoiceBatchConfigPrint
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property ApplicationName() As String
        Get
            Return Me.applicationNameField
        End Get
        Set
            Me.applicationNameField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property LogLevel() As String
        Get
            Return Me.logLevelField
        End Get
        Set
            Me.logLevelField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property ErrorLogSourceFile() As String
        Get
            Return Me.errorLogSourceFileField
        End Get
        Set
            Me.errorLogSourceFileField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property ErrorLogDestination() As String
        Get
            Return Me.errorLogDestinationField
        End Get
        Set
            Me.errorLogDestinationField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property CompanyPlatformID() As String
        Get
            Return Me.companyPlatformIDField
        End Get
        Set
            Me.companyPlatformIDField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Attachment", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Attachment() As CustomerInvoiceBatchConfigAttachment()
        Get
            Return Me.attachmentField
        End Get
        Set
            Me.attachmentField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Fax", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Fax() As CustomerInvoiceBatchConfigFax()
        Get
            Return Me.faxField
        End Get
        Set
            Me.faxField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Email", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Email() As CustomerInvoiceBatchConfigEmail()
        Get
            Return Me.emailField
        End Get
        Set
            Me.emailField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Print", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Print() As CustomerInvoiceBatchConfigPrint()
        Get
            Return Me.printField
        End Get
        Set
            Me.printField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class CustomerInvoiceBatchConfigAttachment
    
    Private buildTiffDestinationField As String
    
    Private buildTiffTempDirField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property BuildTiffDestination() As String
        Get
            Return Me.buildTiffDestinationField
        End Get
        Set
            Me.buildTiffDestinationField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property BuildTiffTempDir() As String
        Get
            Return Me.buildTiffTempDirField
        End Get
        Set
            Me.buildTiffTempDirField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class CustomerInvoiceBatchConfigFax
    
    Private maxRetryField As String
    
    Private noCoverField As String
    
    Private notifyAddressField As String
    
    Private notifyAddressTypeField As String
    
    Private notifyMessageField As String
    
    Private notifySenderNameField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property MaxRetry() As String
        Get
            Return Me.maxRetryField
        End Get
        Set
            Me.maxRetryField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property NoCover() As String
        Get
            Return Me.noCoverField
        End Get
        Set
            Me.noCoverField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property NotifyAddress() As String
        Get
            Return Me.notifyAddressField
        End Get
        Set
            Me.notifyAddressField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property NotifyAddressType() As String
        Get
            Return Me.notifyAddressTypeField
        End Get
        Set
            Me.notifyAddressTypeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property NotifyMessage() As String
        Get
            Return Me.notifyMessageField
        End Get
        Set
            Me.notifyMessageField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property NotifySenderName() As String
        Get
            Return Me.notifySenderNameField
        End Get
        Set
            Me.notifySenderNameField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class CustomerInvoiceBatchConfigEmail
    
    Private fromAddressField As String
    
    Private fromTypeField As String
    
    Private fromNameField As String
    
    Private recipientTypeField As String
    
    Private subjectField As String
    
    Private messageField As String
    
    Private attachOutputNameField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property FromAddress() As String
        Get
            Return Me.fromAddressField
        End Get
        Set
            Me.fromAddressField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property FromType() As String
        Get
            Return Me.fromTypeField
        End Get
        Set
            Me.fromTypeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property FromName() As String
        Get
            Return Me.fromNameField
        End Get
        Set
            Me.fromNameField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property RecipientType() As String
        Get
            Return Me.recipientTypeField
        End Get
        Set
            Me.recipientTypeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Subject() As String
        Get
            Return Me.subjectField
        End Get
        Set
            Me.subjectField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Message() As String
        Get
            Return Me.messageField
        End Get
        Set
            Me.messageField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property AttachOutputName() As String
        Get
            Return Me.attachOutputNameField
        End Get
        Set
            Me.attachOutputNameField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class CustomerInvoiceBatchConfigPrint
    
    Private notifyAddressField As String
    
    Private notifyAddressTypeField As String
    
    Private notifyMessageField As String
    
    Private notifyErrorTemplateField As String
    
    Private attachCopiesField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property NotifyAddress() As String
        Get
            Return Me.notifyAddressField
        End Get
        Set
            Me.notifyAddressField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property NotifyAddressType() As String
        Get
            Return Me.notifyAddressTypeField
        End Get
        Set
            Me.notifyAddressTypeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property NotifyMessage() As String
        Get
            Return Me.notifyMessageField
        End Get
        Set
            Me.notifyMessageField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property NotifyErrorTemplate() As String
        Get
            Return Me.notifyErrorTemplateField
        End Get
        Set
            Me.notifyErrorTemplateField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property AttachCopies() As String
        Get
            Return Me.attachCopiesField
        End Get
        Set
            Me.attachCopiesField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class CustomerInvoiceBatchCustomer
    
    Private faxesField As String
    
    Private printField As String
    
    Private eDIField As String
    
    Private emailsField() As CustomerInvoiceBatchCustomerEmails
    
    Private invoicesField()() As CustomerInvoiceBatchCustomerInvoicesInvoiceNumber
    
    Private idField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Faxes() As String
        Get
            Return Me.faxesField
        End Get
        Set
            Me.faxesField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Print() As String
        Get
            Return Me.printField
        End Get
        Set
            Me.printField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property EDI() As String
        Get
            Return Me.eDIField
        End Get
        Set
            Me.eDIField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Emails", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Emails() As CustomerInvoiceBatchCustomerEmails()
        Get
            Return Me.emailsField
        End Get
        Set
            Me.emailsField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
     System.Xml.Serialization.XmlArrayItemAttribute("InvoiceNumber", GetType(CustomerInvoiceBatchCustomerInvoicesInvoiceNumber), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
    Public Property Invoices() As CustomerInvoiceBatchCustomerInvoicesInvoiceNumber()()
        Get
            Return Me.invoicesField
        End Get
        Set
            Me.invoicesField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property ID() As String
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class CustomerInvoiceBatchCustomerEmails
    
    Private emailField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property Email() As String
        Get
            Return Me.emailField
        End Get
        Set
            Me.emailField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class CustomerInvoiceBatchCustomerInvoicesInvoiceNumber
    
    Private filePathsField() As CustomerInvoiceBatchCustomerInvoicesInvoiceNumberFilePaths
    
    Private valueField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("FilePaths", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property FilePaths() As CustomerInvoiceBatchCustomerInvoicesInvoiceNumberFilePaths()
        Get
            Return Me.filePathsField
        End Get
        Set
            Me.filePathsField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Value() As String
        Get
            Return Me.valueField
        End Get
        Set
            Me.valueField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class CustomerInvoiceBatchCustomerInvoicesInvoiceNumberFilePaths
    
    Private invoicePathField As String
    
    Private deliveryTicketPathField As String
    
    Private bOLPathField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property InvoicePath() As String
        Get
            Return Me.invoicePathField
        End Get
        Set
            Me.invoicePathField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property DeliveryTicketPath() As String
        Get
            Return Me.deliveryTicketPathField
        End Get
        Set
            Me.deliveryTicketPathField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
    Public Property BOLPath() As String
        Get
            Return Me.bOLPathField
        End Get
        Set
            Me.bOLPathField = value
        End Set
    End Property
End Class
